<?php
/**
 * Implementation of hook_views_api().
 */
function views_limit_grouping_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Load the views .inc files.
 */
module_load_include('inc', 'views_limit_grouping', 'templates/views_limit_grouping.views');

/**
 * Implementation of hook_autoload_info().
 */
function views_limit_grouping_autoload_info() {
  return array(
    'views_limit_grouping_style_plugin' => 'includes/views_limit_grouping_style_plugin.inc',
  );
}

