<?php
  
/**
 * Implementation of hook_views_api().
 */
function views_limit_grouping_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_limit_grouping') . '/views',
  );
}

/**
 * Implementation of hook_autoload_info().
 */
function views_limit_grouping_autoload_info() {
  return array(
    'views_limit_grouping_style_plugin' => 'includes/views_limit_grouping_style_plugin.inc',
  );
}

