<?php

// Load the .inc file.

module_load_include('inc', 'views_limit_grouping', 'views_limit_grouping.views');


/**
 * @file
 * Just declaring Views dependancy; nothing much to see here.
 */

/**
 * Implementation of hook_views_api().
 */
function views_limit_grouping_views_api() {
  return array(
    'api' => 3,
  );
}

function views_limit_grouping_autoload_info() {
  return array(
    'views_limit_grouping_style_plugin' => 'includes/views_limit_grouping_style_plugin.inc',
  );
}

